//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.MVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewModelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewModelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inventory.MVC.Resources.ViewModelResources", typeof(ViewModelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:dd.mm.yyyy &apos;г.&apos;}.
        /// </summary>
        public static string DateFormatString {
            get {
                return ResourceManager.GetString("DateFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изберете дата.
        /// </summary>
        public static string DateFormatStringEmptyMessage {
            get {
                return ResourceManager.GetString("DateFormatStringEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:dd.mm.yyyy &apos;г.&apos;  H:mm:ss}.
        /// </summary>
        public static string DateTimeFormatString {
            get {
                return ResourceManager.GetString("DateTimeFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изберете дата и час.
        /// </summary>
        public static string DateTimeFormatStringEmptyMessage {
            get {
                return ResourceManager.GetString("DateTimeFormatStringEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string ElementViewModel_Name_Name {
            get {
                return ResourceManager.GetString("ElementViewModel_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индустрия.
        /// </summary>
        public static string Industry {
            get {
                return ResourceManager.GetString("Industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Община.
        /// </summary>
        public static string Municipality {
            get {
                return ResourceManager.GetString("Municipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изберете дата.
        /// </summary>
        public static string PlaceHolderTextDate {
            get {
                return ResourceManager.GetString("PlaceHolderTextDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изберете дата и час.
        /// </summary>
        public static string PlaceHolderTextDateTime {
            get {
                return ResourceManager.GetString("PlaceHolderTextDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете число ....
        /// </summary>
        public static string PlaceHolderTextDecimal {
            get {
                return ResourceManager.GetString("PlaceHolderTextDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете цяло число ....
        /// </summary>
        public static string PlaceHolderTextLong {
            get {
                return ResourceManager.GetString("PlaceHolderTextLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете текст ....
        /// </summary>
        public static string PlaceHolderTextString {
            get {
                return ResourceManager.GetString("PlaceHolderTextString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете дата ....
        /// </summary>
        public static string PlaceHolderTextStringDate {
            get {
                return ResourceManager.GetString("PlaceHolderTextStringDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изберете стойност ....
        /// </summary>
        public static string PlaceHolderTextStringForeignKey {
            get {
                return ResourceManager.GetString("PlaceHolderTextStringForeignKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        public static string ProductCategory {
            get {
                return ResourceManager.GetString("ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Склад.
        /// </summary>
        public static string ProductStore {
            get {
                return ResourceManager.GetString("ProductStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мярка.
        /// </summary>
        public static string ProductUnitMeasure {
            get {
                return ResourceManager.GetString("ProductUnitMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        public static string ProductViewModel_CategoryId_Name {
            get {
                return ResourceManager.GetString("ProductViewModel_CategoryId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание на код.
        /// </summary>
        public static string ProductViewModel_Code_Description {
            get {
                return ResourceManager.GetString("ProductViewModel_Code_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        public static string ProductViewModel_Code_Name {
            get {
                return ResourceManager.GetString("ProductViewModel_Code_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля въведете код.
        /// </summary>
        public static string ProductViewModel_Code_Prompt {
            get {
                return ResourceManager.GetString("ProductViewModel_Code_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код (съкр.).
        /// </summary>
        public static string ProductViewModel_Code_ShortName {
            get {
                return ResourceManager.GetString("ProductViewModel_Code_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string ProductViewModel_Name_Name {
            get {
                return ResourceManager.GetString("ProductViewModel_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Праг.
        /// </summary>
        public static string ProductViewModel_ReorderLevel_Name {
            get {
                return ResourceManager.GetString("ProductViewModel_ReorderLevel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Край продажба.
        /// </summary>
        public static string ProductViewModel_SellEndDate_Name {
            get {
                return ResourceManager.GetString("ProductViewModel_SellEndDate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало продажба.
        /// </summary>
        public static string ProductViewModel_SellStartDate_Name {
            get {
                return ResourceManager.GetString("ProductViewModel_SellStartDate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Склад.
        /// </summary>
        public static string ProductViewModel_StoreId_Name {
            get {
                return ResourceManager.GetString("ProductViewModel_StoreId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мярка.
        /// </summary>
        public static string ProductViewModel_UnitMeasureId_Name {
            get {
                return ResourceManager.GetString("ProductViewModel_UnitMeasureId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string ProductViewModel_UnitPrice_Name {
            get {
                return ResourceManager.GetString("ProductViewModel_UnitPrice_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        public static string ProductViewModel_UnitsInStock_Name {
            get {
                return ResourceManager.GetString("ProductViewModel_UnitsInStock_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поръчано.
        /// </summary>
        public static string ProductViewModel_UnitsOnOrder_Name {
            get {
                return ResourceManager.GetString("ProductViewModel_UnitsOnOrder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регион.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето {0} е задължително!.
        /// </summary>
        public static string RequiredErrorMessage {
            get {
                return ResourceManager.GetString("RequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Град.
        /// </summary>
        public static string Town {
            get {
                return ResourceManager.GetString("Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string ViewModel_Id {
            get {
                return ResourceManager.GetString("ViewModel_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създаден от.
        /// </summary>
        public static string ViewModelBase_CreatedBy_Name {
            get {
                return ResourceManager.GetString("ViewModelBase_CreatedBy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създаден на.
        /// </summary>
        public static string ViewModelBase_CreatedOn_Name {
            get {
                return ResourceManager.GetString("ViewModelBase_CreatedOn_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Променен от.
        /// </summary>
        public static string ViewModelBase_ModifiedBy_Name {
            get {
                return ResourceManager.GetString("ViewModelBase_ModifiedBy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Променен на.
        /// </summary>
        public static string ViewModelBase_ModifiedOn_Name {
            get {
                return ResourceManager.GetString("ViewModelBase_ModifiedOn_Name", resourceCulture);
            }
        }
    }
}
